# docker-compose.yml
version: '3.2'
services:
   jupyter-notebook:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - NOTEBOOK_ARGS=--port 8080
    ports:
      - '8080:8080'
    container_name: jupyter-notebook
    restart: "no"